name: Michael Kang
description: Personal website
menu:
 - page: About
   url: /about
 - page: Papers
   url: /papers
   links:
    - title: Working papers
      url: "#working-papers"
    - title: Published papers
      url: "#published-papers"
 - page: Research Projects
   url: /research
   links:
    - title: "Project One"
      url: "#project-one"
    - title: "Project Two"
      url: "#project-two"
    - title: "Project Three"
      url: "#project-three"
    - title: "Project Four"
      url: "#project-four"
 - page: Curriculum Vitae
   url: /cv
   links:
    - title: Experience
      url: "#experience"
    - title: Education
      url: "#education"
    - title: Positions
      url: "#positions"
    - title: Miscellaneous
      url: "#miscellaneous"
 - page: Logs
   url: /logs
 - page: Media
   url: /media
 - page: Accolades
   url: /accolades
menu_external:
 - title: Research Gate
   url: ""
 - title: LinkedIn
   url: ""
 - title: Twitter
   url: ""
mathjax: false
markdown: kramdown
encoding: utf-8
baseurl: Kangroo12345678.github.io
locale: en_GB
